import 'package:first_app/models/meal.dart';
import 'package:flutter/material.dart';
import 'models/category.dart';
import 'models/meal.dart';
//import 'package:url_launcher/url_launcher.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Итали',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Хөнгөн хоол',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Гамбургер',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Герман',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Зууш',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Өвөрмөц хоол',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Өглөөний цай',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Ази',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Франц',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Хээрийн хоол',
    color: Colors.teal,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m1.png',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Сонгино лууван, бэлдсэн шар буурцгын мах, төмсөө холих холицоо бэлдэнэ.',
      'Гурилаа жижиглэж тасдаад хэрчинэ ',
      'Ингээд л бэлэн болно.',
      'та ширээгээ өөрийн дуртай зуушны хамт чимэглэн засаад л өөрийн хийсэн гайхалтай хоолийг амтлаарай.',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: true,
    isVegetarion: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m2.png',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Songino beldeed yaana yaana',
      'GUrilaa jijigleed ',
      'Ingeed l belen bolchihno',
      'tanii shiree',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarion: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m3.png',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Songino beldeed yaana yaana',
      'GUrilaa jijigleed ',
      'Ingeed l belen bolchihno',
      'tanii shiree',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarion: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m4.jpg',
    //'http://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Сонгино лууван, бэлдсэн шар буурцгын мах, төмсөө холих холицоо бэлдэнэ.',
      'Гурилаа жижиглэж тасдаад хэрчинэ ',
      'Ингээд л бэлэн болно.',
      'та ширээгээ өөрийн дуртай зуушны хамт чимэглэн засаад л өөрийн хийсэн гайхалтай хоолийг амтлаарай.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarion: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m5.jpg',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Songino beldeed yaana yaana',
      'GUrilaa jijigleed ',
      'Ingeed l belen bolchihno',
      'tanii shiree',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarion: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'assets/image/m6.jpg',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Сонгино лууван, бэлдсэн шар буурцгын мах, төмсөө холих холицоо бэлдэнэ.',
      'Гурилаа жижиглэж тасдаад хэрчинэ ',
      'Ингээд л бэлэн болно.',
      'та ширээгээ өөрийн дуртай зуушны хамт чимэглэн засаад л өөрийн хийсэн гайхалтай хоолийг амтлаарай.',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarion: true,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m7.jpg',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Songino beldeed yaana yaana',
      'GUrilaa jijigleed ',
      'Ingeed l belen bolchihno',
      'tanii shiree',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarion: true,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl: 'assets/image/m8.jpg',
    //'http://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 20,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Сонгино лууван, бэлдсэн шар буурцгын мах, төмсөө холих холицоо бэлдэнэ.',
      'Гурилаа жижиглэж тасдаад хэрчинэ ',
      'Ингээд л бэлэн болно.',
      'та ширээгээ өөрийн дуртай зуушны хамт чимэглэн засаад л өөрийн хийсэн гайхалтай хоолийг амтлаарай.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: false,
    isVegetarion: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'assets/image/m9.jpg',
    //'http://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '4 төмс',
      '1 халбага оливийн тос',
      '1 сонгино',
      '250гр',
      'халуун ногоо',
      'бяслаг'
    ],
    steps: [
      'Songino beldeed yaana yaana',
      'GUrilaa jijigleed ',
      'Ingeed l belen bolchihno',
      'tanii shiree',
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarion: true,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Помидорны соустай шпагетти',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'assets/image/m10.jpg',
    //'http://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'гурил-200гр',
      'Лууван-50гр',
      'төмс-50гр',
      'шар буурцагны мах -50гр',
      'ургамлын тос',
    ],
    steps: [
      'Сонгино лууван, бэлдсэн шар буурцгын мах, төмсөө холих холицоо бэлдэнэ.',
      'Гурилаа жижиглэж тасдаад хэрчинэ ',
      'Ингээд л бэлэн болно.',
      'та ширээгээ өөрийн дуртай зуушны хамт чимэглэн засаад л өөрийн хийсэн гайхалтай хоолийг амтлаарай.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarion: true,
  ),
];
